### ISSUE TITLE
Getting a large number of block artifacts in prediction output even though I have considerable overlap?

### ISSUE THREAD

**Issue by StuckinPhD** [wolny/pytorch-3dunet#34]
The output generated by ``predict.py`` is very messy and has very ugly and noticeable block artifacts. 
Below is my ``test_config.yaml`` file and as you can see I have considerable overlap. Yet I am getting a lot of block artifacts. 

The segmentation result is very acceptable but due to these artifacts it is useless, can you please suggest how to improve/fix this?

```
# path to the checkpoint file containing the model
model_path: 3dunet/best_checkpoint.pytorch
# model configuration
model:
  # model class
  name: ResidualUNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: cge
  # feature maps scale factor
  f_maps: 32
  # basic module - Choose between (ExtResNetBlock or DoubleConv)
  basic_module: ExtResNetBlock
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# specify the test datasets
datasets:
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [32, 192, 192]
  # stride between patches (make sure the the patches overlap in order to get smoother prediction maps)
  stride: [8, 96, 96]
  # path to the raw data within the H5
  raw_internal_path: raw
  # how many subprocesses to use for data loading
  num_workers: 0
  # paths to the datasets
  test_path:
    - 'test_hdf5/test_file.h5'
  transformer:
    test:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true
```
